services:
  web:
    container_name: nginx_proxy
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/nginx/conf:/etc/nginx/conf.d
      - /var/nginx/ssl:/etc/nginx/certs
      - /var/nginx/log:/etc/nginx/log
    networks:
      - nginx_network



networks:
  nginx_network:
    external: true
