
services:
  web:
    container_name: nginx_proxy
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/nginx/conf:/etc/nginx/conf.d
    networks:
      - nginx_network



networks:
  nginx_network:
    external: true
