apiVersion: apps/v1
kind: Deployment
metadata:
  name: nst-site
spec:
  selector:
    matchLabels:
      nst-site
  template:
    metadata:
      labels:
        nst-site
    spec:
      containers:
      - nst-site
        image: registry.tomskasu.ru/nst-site/nst-site:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nst-site
spec:
  selector:
    app: nst-site
  ports:
  - port: 80
    targetPort: 8080

